# Site settings
title: Efficience Software
email: contact@efficiencesoftware.fr
phone: (+596) 696 29 79 69
description: > # this means to ignore newlines until "baseurl:"
    Efficience Software aide votre entreprise à atteindre ses objectifs en vous accompagnant dans le choix et la mise en oeuvre de solutions adaptées à vos besoins.
baseurl: ""
url: http://www.efficiencesoftware.fr

img: /img/connection.png

# Build settings
markdown: kramdown
permalink: pretty

collections:
    services:
        output: true
        permalink: /services/:path/

gems:
    - jekyll-sitemap
