# Site settings
title: Efficience Software
email: contact@efficiencesoftware.fr
phone: (+596) 696 29 79 69
description: > # this means to ignore newlines until "baseurl:"
    Efficience Software, agence web en Martinique. Transformez votre entreprise avec le num√©rique (Site web et mobile, Microsoft Dynamics CRM, Salesforce).
baseurl: ""
url: http://www.efficiencesoftware.fr

img: http://res.cloudinary.com/efficiencesoftware/image/upload/v1459366287/team_did6sv.jpg

# Build settings
markdown: kramdown
permalink: pretty

collections:
  tools:
    output: false
  services:
    output: true
    permalink: /services/:path/

gems:
    - jekyll-sitemap
